# Generated by Django 2.2 on 2019-04-02 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Branch_manager',
        ),
        migrations.AddField(
            model_name='profile',
            name='branch_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='head_manager',
            field=models.BooleanField(default=False),
        ),
    ]
