# Generated by Django 2.2 on 2019-04-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorgroup',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
