# Generated by Django 2.2 on 2019-04-04 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('errors', '0002_auto_20190404_1137'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='error',
            unique_together={('error_group', 'name')},
        ),
    ]
