# Generated by Django 2.2 on 2019-04-05 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('errors', '0003_auto_20190404_1139'),
        ('products', '0004_product_in_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('o', 'Open'), ('s', 'Send'), ('i', 'In Progress'), ('c', 'Closed')], default='o', max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('error', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='errors.Error')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
