# Generated by Django 2.2 on 2019-04-03 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_auto_20190402_0302'),
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='system',
            unique_together={('branch', 'name')},
        ),
    ]
