# Generated by Django 2.2 on 2019-04-10 20:04

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('systems', '0001_initial'),
        ('errors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('image', models.ImageField(blank=True, default='/product.png', null=True,
                                            upload_to=products.models.upload_location)),
                ('in_request', models.BooleanField(default=False)),
                ('res_time', models.FloatField(blank=True, help_text='Per Hours', null=True)),
                ('fix_time', models.FloatField(blank=True, help_text='Per Hours', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('error_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                  to='errors.ErrorGroup')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.System')),
            ],
            options={
                'unique_together': {('system', 'code')},
            },
        ),
    ]
