# Generated by Django 2.2 on 2019-04-04 11:25

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/product.png', null=True, upload_to=products.models.upload_location),
        ),
    ]
