# Generated by Django 2.2 on 2019-04-04 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('errors', '0001_initial'),
        ('products', '0002_auto_20190404_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='error_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='errors.ErrorGroup'),
        ),
    ]
