# Generated by Django 2.2 on 2019-04-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_error_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_request',
            field=models.BooleanField(default=False),
        ),
    ]
